### ISSUE TITLE
Substitution of placehoders in mail doesn't work

### ISSUE THREAD

**Issue by al66** [justb3a/processwire-newslettersubscription#2]
Thanks for the module!

Just the placeholder substitution doens't work.
It seems to be an error in:
 private function getMessageContent($name, $link, $user, $text) {

I have replaced 
   if (count($user) === 1) {
with
  if (isset($user)) {
Now it works for me.

Best regards,
Andreas

**Comment by justb3a** [comment]
Hi,you're right. `count($user)` returns `(int)0`. I just pushed a hotfix. Thanks!
